### ISSUE TITLE
bounding_box_to_coordinate_system.py

### ISSUE THREAD

**Issue by YangLuhong** [agisoft-llc/photoscan-scripts#1]
hello,I want to use python scripts in photoscan, but I met some problems, could I get some help?
you use it in release 1.4, so could I use in Release 1.2, or should I update my photoscan?
then, how to use these scripts?  when i use the tools->run scripts, nothing happened.
thanks for your reply.

**Comment by PolarNick239** [comment]
Hello.

You should update your PhotoScan because PhotoScan API changes from release to release and some scripts can be backward incompatible.

After executing ```Tools->Run Script...``` you should check newly appeared ```Custom menu``` button next to ```Tools``` and ```Help```. Script added its feature to that dropdown list (```Custom menu -> Bounding box to coordinate system```).

Also please note that if you need to run some scripts on each PhotoScan launch - you can do this [automatically](https://agisoft.freshdesk.com/support/solutions/articles/31000133123-how-to-run-python-script-automatically-on-photoscan-professional-start). So ```Custom menu``` will appear on each launch.
